### ISSUE TITLE
CI/CD is missing

### ISSUE THREAD

**Issue by gpengzhi** [graph4ai/graph4nlp#307]
Thanks for your wonderful job! 

I notice that there is no CI/CD pipeline (unit test, lint test, etc.) in your project. As an NLP toolkit, I think it is extremely important to guarantee the correctness and readability of your code. Maybe you could consider adding those in your repo, which should be helpful for your future development.

**Comment by AlanSwift** [comment]
Thanks for your suggestion. We will add the CI component soon.
