### ISSUE TITLE
Graph2Tree model and prediction

### ISSUE THREAD

**Issue by maurovit** [graph4ai/graph4nlp#316]
Hello, 
I followed your tutorial about semantic parsing with graph2tree on Jobs Data and I have two question. 
I wonder how can I manage model and new unseen data for prediction: in particular 

1. how can I save the model after training? Should I use the classical torch instruction to save the model like
                        `torch.save(model.state_dict(), PATH)` or `torch.save(model, PATH)`
2. After that I want to make prediction about unseen data: to do this should I follow the instruction of eval method in the Jobs class?

Thank you 🙇

**Comment by schenglee** [comment]
hi, @maurovit, thank you for your feedback. For the two questions,
- Yes, you can use ``torch.save`` to save your checkpoints.  
- Yes, you should follow the ``eval`` method to do inference. For unseen data, you just need to remove the evaluation process.

**Comment by maurovit** [comment]
Thank you @schenglee for your answer, but i have some doubts: i cannot fully understand how I can pass the data to the model for inference. In particular, for the evaluation I see that the model retrieves the data from the test data-loader, which is generate from JobsDatasetForTree. This is different from my goals: I want to pass to model a list of strings, preprocess these strings (according to the method that I used in the training, i.e. Dependency or Constituency or something else) and do inference on this data. Can you explain me how i can do that? Thanks
