### ISSUE TITLE
Additional Text Classification dataset

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#323]
## 🚀 Feature

Include Twitter Sentiment dataset for Text Classification sample

## Motivation

Twitter Sentiment dataset is popular for learning Text classification. Incorporating it here would help check effectiveness of GNNs with respect to existing Machine/Deep Learning approaches

## Pitch

Similar to 'Trec' dataset present, 'Twitter' dataset can be added.

## Additional context

The Twitter dataset is on similar lines as that of https://www.kaggle.com/divakarsarma/sentiment-analysis

**Comment by yogeshhk** [comment]
I am ready to volunteer for this submission

**Comment by AlanSwift** [comment]
Welcome! Thank you for your interest and contribution!

**Comment by yogeshhk** [comment]
@AlanSwift  As mentioned before, I can implement this and send it to you all for review via pull request

**Comment by AlanSwift** [comment]
@yogeshhk Yes, I will review your pr. We are expecting your excellent contribution!

**Comment by Nicoleqwerty** [comment]
Hi @yogeshhk, could you please offer a download link to the processed Twitter Sentiment dataset which can be downloaded directly using **wget**? Due to storage limitations, we will not add any more datasets to our repo. Thank you!

**Comment by yogeshhk** [comment]
Ok, got it. Thanks for the response.
