### ISSUE TITLE
Error while parsing line

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#325]
## 🐛 Bug

Error may occur while parsing training dataset lines.

## To Reproduce

1. Get dataset with some non-formatted lines, meaning TAB separated lines
2. Try to run Text Classifier
3. Errors out from the operation fully.

## Expected behavior
Skip the error line and proceed with other lines.

## Possible Solution

Should it be addressed in graph4nlp\pytorch\data\dataset.py for
class Text2LabelDataset in parse_file() as below?

```
        data = []
        with open(file_path, 'r', encoding="utf-8") as f:
            for line in f:
                try:
                    input, output = line.split('\t')
                    data_item = Text2LabelDataItem(input_text=input.strip(), output_label=output.strip(),
                                                   tokenizer=self.tokenizer)
                    data.append(data_item)
                except Exception as msg:
                    warnings.warn(RuntimeWarning(msg))

        return data

```
## Environment

 - Graph4NLP Version (e.g., 0.4.1):
 - Backend Library & Version (e.g., PyTorch 1.6.0): 1.8
 - OS (e.g., Linux): Windows 10
 - How you installed Graph4NLP (`pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): CPU
 - GPU models and configuration (e.g. 2080Ti):
 - Any other relevant information:

**Comment by AlanSwift** [comment]
If you want to parse your own dataset, you should create a new dataset class that inherits our ``Dataset`` and override the parse function. We would address this problem in the coming version's the documents.

**Comment by AlanSwift** [comment]
This will be an important feature for the next coming version.
