### ISSUE TITLE
Inferencing from Text

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#326]
## ❓ Questions and Help

Looking at evaluating TextClassifier from

`python examples/pytorch/text_classification/run_text_classifier.py -config examples/pytorch/text_classification/config/trec/ggnn_bi_fuse_constituency.yaml`

run_text_classifier 'main()' does training and testing using data loaders.

Wish to test the trained model, by supplying sample text directly. meaning, can I predict label by giving text?

TextClassifier to have following method:

```
def predict(self, texts):
	predicted_labels = model.foo(texts)
	return predicted_labels
```

**Comment by AlanSwift** [comment]
``TextClassifier`` only receives the ``GraphData`` object (not the raw texts). 

As we discussed in [#319 (issue)](https://github.com/graph4ai/graph4nlp/issues/319), currently this feature is natively supported. If you want to decouple the training and inference stages, you could implement it by constructing the ``GraphData`` given raw text inputs during inference.

**Comment by AlanSwift** [comment]
It will be an important feature in the next version. Thank you!
