### ISSUE TITLE
GPU flag in NER tutorial

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#328]
## 🐛 Bug

In the given tutorial sample program

`python examples/pytorch/name_entity_recognition/main.py   --graph_type dependency_graph --gpu 0 --init_hidden_size 400 --hidden_size 128  --lr 0.01 --batch_size 100 --gnn_type graphsage --direction_option undirected`

Option for gpu given is '0'. Simple interpretation is that its for NO GPU ie CPU. On a CPU machine `--gpu 0` gives error that Pytorch was not built using GPU.

## Possible Resolution

Reason is that the internal code being as below, it still treats it as GPU.

```
        if args.gpu>-1:
            self.device = torch.device('cuda') 
        else:
             self.device = torch.device('cpu')
```

Should it be changed to?

```
        if args.gpu>0::
            self.device = torch.device('cuda') 
        else:
             self.device = torch.device('cpu')
```

so that `--gpu 0` behaves as CPU and `--gpu 1` behaves as GPU?

## Environment

 - Graph4NLP Version (e.g., 0.4.1):
 - Backend Library & Version (e.g., PyTorch 1.6.0):.1.18.1
 - OS (e.g., Linux): Windows 10
 - How you installed Graph4NLP (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.6.5
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. 2080Ti):
 - Any other relevant information:

**Comment by AlanSwift** [comment]
Thank you for your suggestion!
From our design, ``--gpu -1`` means the ``cpu`` choice. And the ``--gpu 0``behaves as  ``gpu`` with ID 0.

**Comment by yogeshhk** [comment]
Ok, got it. Thanks for the response.
