### ISSUE TITLE
Tolerant file parsing

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#332]
## 🐛 Bug

Strict whitespace formatting is needed for IOB data file. Can it be relaxed to have any number of whitespaces including tabs.

## To Reproduce

1. Have tab separated IOB file
2. Data does not get read.
3. No processing happens

## Possible solution
 In graph4nlp\pytorch\data\dataset.py in parse_file()  in place of

```
                        input.append(line.strip().split(' ')[0])
                        output.append(line.strip().split(' ')[-1])
```

can it be:

```
                        words = [w.strip() for w in line.split()]
                        input.append(words[0])
                        output.append(words[-1]) # POS tags and Phrase etc in-between are ignored
```

## Environment

 - Graph4NLP Version (e.g., 0.4.1):
 - Backend Library & Version (e.g., PyTorch 1.6.0):
 - OS (e.g., Linux):
 - How you installed Graph4NLP (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. 2080Ti):
 - Any other relevant information:

**Comment by AlanSwift** [comment]
Thanks for your valuable advice! We are sorry for the late reply.
However, I can't fully understand your point. It seems the default separator in ``str.split()`` is any whitespace and we actually use `` ``(blankspace). Is this the problem?

**Comment by yogeshhk** [comment]
Found issue if sometimes tabs are present or sometime multiple spaces are present between word and label.

**Comment by AlanSwift** [comment]
Ok. However, we will discuss this problem in our meeting since this change may affect the existing examples.
Notes: We highly recommend you inherit the Dataset's parse_file() function the default parsing function can't meet your need.
