### ISSUE TITLE
Approach/paper for NER?

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#333]
## ❓ Questions and Help

Wish to know which approach has been taken, or which paper has been referred while implementing Named Entity Recognition (NER) in graph4nlp?

**Comment by xguo7** [comment]
Thanks for your interest in this library. The implementation of NER task is mainly based on the paper: GraphIE: A Graph-Based Framework for Information Extraction (https://aclanthology.org/N19-1082.pdf). The results reported are without CRF module.

**Comment by xguo7** [comment]
> ## ❓ Questions and Help
> Wish to know which approach has been taken, or which paper has been referred while implementing Named Entity Recognition (NER) in graph4nlp?

Thanks for your interest in this library. The implementation of NER task is mainly based on the paper: GraphIE: A Graph-Based Framework for Information Extraction (https://aclanthology.org/N19-1082.pdf). The results reported are without CRF module.

**Comment by yogeshhk** [comment]
Thanks for the reference to the paper.
