### ISSUE TITLE
Graph Encoder Decoder

### ISSUE THREAD

**Issue by yogeshhk** [graph4ai/graph4nlp#334]
## ❓ Questions and Help

Is it possible to have supervised end-to-end Graph neural network for Encoder-Decoder architecture, where both, input and output graphs are of different topology.

Example: Summarization, when both, original text and its summary are modeled as graphs with different topologies.

Does DGL or Graph4nlp support such supervised learning architecture? 

If yes, there is another use-case for such GNN, in geometric modeling, explained in details at https://github.com/yogeshhk/MidcurveNN  just FYI

**Comment by AlanSwift** [comment]
Thanks for your valuable opinion.
I think you mean the graph-to-graph applications, in which one cast the inputs (texts, graphs, etc.) to graph and then predicts another graph as output.
If yes, we highly recommend you our survey paper: [Graph Neural Networks for Natural Language Processing: A Survey](https://arxiv.org/abs/2106.06090). We have comprehensively discussed this topic. 
As for the code, currently, there are no exactly graph2graph examples in our library. However, Graph2Tree is a close task.

**Comment by AlanSwift** [comment]
I will close this issue.
