### ISSUE TITLE
Hard coded word embedding size in vocab_utils.py

### ISSUE THREAD

**Issue by gianlucamacri** [graph4ai/graph4nlp#382]
## 🐛 Bug

In the file [/graph4nlp/pytorch/modules/utils/vocab_utils.py](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/utils/vocab_utils.py) the init function of  WordEmbModel has the number 300 hardcoded for selecting the cache file when GloVe is used.

<pre>
class WordEmbModel(Vectors):
    def __init__(self, pretrained_word_emb_name="840B", pretrained_word_emb_url=None, pretrained_word_emb_cache_dir=".vector_cache/"):
        
        if pretrained_word_emb_name in GloVe.url.keys() and pretrained_word_emb_url is None:
            url = GloVe.url[pretrained_word_emb_name]
            name = 'glove.{}.{}d.txt'.format(pretrained_word_emb_name, <b>str(300)</b>)
</pre>

This can be incoherent with Dataset parameter 'word_emb_size', and can throw an error when there is no embedding file with that dimension, e.g. when using 'twitter.27B' as pretrained_word_emb_name.

## Expected behavior

Select the correct cache file based on 'word_emb_size' parameter when using GloVe word embeddings.

## Additional context

**Temporary workaround**: define dataset setting 'pretrained_word_emb_name' with the full cache filename (e.g. "glove.twitter.27B.200d.txt") and use 'pretrained_word_emb_url' accordingly.

**Comment by AlanSwift** [comment]
Thank you for letting us know. Yes, we will fix it soon!

**Comment by AlanSwift** [comment]
This bug has been fixed in the develop branch. Thus I will close it and please feel free to ask questions if you still have any problems.
