### ISSUE TITLE
difference b/w pretrained_word_emb_name and emb_strategy ?

### ISSUE THREAD

**Issue by saneshashank** [graph4ai/graph4nlp#396]
## ❓ Questions and Help

Hi,

In the .yaml config files provided in example I can see that there are two tags "_pretrained_word_emb_name_" which for example can be set to 6B which use Glove to create node embeddings, however there is also another tag "_emb_strategy_" where you can define for example "w2v" or "bert" embeddings to be used for node embeddings. Does one of the tags supersedes the other, if not what is the difference of usage between the two ?

Regards,
Shashank

**Comment by AlanSwift** [comment]
Hi,

We are sorry for the unclarity. Yes, they are incompatible. ``pretrained_word_emb_name`` indicates the pre-trained embedding name which is only used when ``w2v`` is set. If you choose ``bert``, the ``pretrained_word_emb_name`` is superseded.

**Comment by saneshashank** [comment]
Hi AlanSwift,

Many thanks for the clarification, that makes sense given the output that I was observing, It would be great if you guys can add a documentation section specifically for configuration items, in its current state its bit confusing.

**Comment by AlanSwift** [comment]
Thanks for your advice! I will clarify it in our documentation.
