### ISSUE TITLE
Error if emb_strategy is set to "w2v"

### ISSUE THREAD

**Issue by saneshashank** [graph4ai/graph4nlp#400]
## 🐛 Bug

The following error occurs if you set "emb_strategy = 'w2v" in the embedding_style dictionary. (with pretrained_word_emb_name having some value example - "6B":

`graph4nlp\pytorch\data\data.py", line 844, in <listcomp>
    individual_features = [value[i, :self._batch_num_nodes[i]] for i in range(len(self._batch_num_nodes))]
TypeError: list indices must be integers or slices, not tuple`

## To Reproduce

1. use gnn_icm_ner.py as reference
2. set _pretrained_word_emb_name = "6B"_
3. set _'emb_strategy': 'w2v'_
4.  run gnn_icm_ner.py

## Environment

 - Graph4NLP Version :0.4.1
 - Backend Library & Version :PyTorch 1.9.0
 - OS (e.g., Linux): Windows

## Additional context

I have found out what the issue is, the bug is in file _embedding_construction.py_  line 272 to 275 below:

        `if self.seq_info_encode_layer is None and 'seq_bert' not in self.word_emb_layers:
            batch_gd.batch_node_features["node_feat"] = feat

            return batch_gd`

instead it should be,

       ` if self.seq_info_encode_layer is None and 'seq_bert' not in self.word_emb_layers:
            feat = torch.cat(feat, dim=-1) # this line should be added as in other blocks
            batch_gd.batch_node_features["node_feat"] = feat

            return batch_gd`

This is because in this code below (which executes if w2v is set as emb_strategy), `feat` is not converted to tensor (line 244-247):

            `if 'w2v' in self.word_emb_layers:
                word_feat = self.word_emb_layers['w2v'](token_ids).squeeze(-2)
                word_feat = dropout_fn(word_feat, self.word_dropout, shared_axes=[-2], training=self.training)
                feat.append(word_feat)`

As batch_gd does not contain a tensor, it gives and error at line `individual_features = [value[i, :self._batch_num_nodes[i]] for i in range(len(self._batch_num_nodes))]` data.py file,  
Kindly check and confirm!!

**Comment by xiao03** [comment]
Hey @saneshashank, sorry for this late reply. We are now working on it.

**Comment by hugochan** [comment]
@saneshashank Thanks for reporting the bug! We reproduced the reported bug following the suggested setting. A fix PR #407 was submitted which should be merged to the develop branch soon. We will be releasing a new version to the master branch very soon. Please stay tuned. 

Closed this issue. Please feel free to reopen it if you still observe the error.
