### ISSUE TITLE
Why is build_vocab() called twice in Dataset class initialization ?

### ISSUE THREAD

**Issue by saneshashank** [graph4ai/graph4nlp#401]
## ❓ Questions and Help

Hi,
I noticed that build_vocab() has been called twice in class initialization of Dataset class, it is called once from self._process() (line 363, dataset.py) and then again in the end separately (at line 372). Is it because of some reason or is it a miss ??

**Comment by xiao03** [comment]
Hey @saneshashank, thank you for letting us know. We are currently working on this issue. Stay tuned for a future update!

**Comment by schenglee** [comment]
Hi, @saneshashank, thanks for your feedback, we have fixed it in #331, please reinstall lib from branch ``develop`` (install by source code).

**Comment by xiao03** [comment]
Issue resolved and closed.
