### ISSUE TITLE
How to predict edges for a Null graph?

### ISSUE THREAD

**Issue by 12seetharaman** [graph4ai/graph4nlp#406]
I'm working on an information retrieval problem from the tables. Taking all the cells in a table as a node. Now, I want to predict all connections (edges) between cells (nodes). 
Is there any way to do it with dlg4nlp?

**Comment by hugochan** [comment]
> I'm working on an information retrieval problem from the tables. Taking all the cells in a table as a node. Now, I want to predict all connections (edges) between cells (nodes).
> Is there any way to do it with dlg4nlp?

@12seetharaman thanks for your interest to our library! Regarding your use case, you might want to take a look into dynamic graph construction which can jointly learn graph structure and graph representations with respect to the downstream prediction task. You might want to follow this [example](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/text_classification/run_text_classifier.py) to learn how to call our dynamic graph construction APIs to suit your need.

**Comment by xiao03** [comment]
Issue resolved and closed.

**Comment by 12seetharaman** [comment]
Thanks, @hugochan, Really helpful!
