### ISSUE TITLE
non deterministic behaviour using graphsage and pool

### ISSUE THREAD

**Issue by gianlucamacri** [graph4ai/graph4nlp#418]
I'm currently facing issues som while using graphsage as gnn and graphsage_aggreagte_type equal to 'pool': despite tsetting seeds and using a single worker to achieve a deteministic behaviour i cannot succeed in that. On the other hand, when using other aggregation types (mean, lstm and gcn) I am able reproduce the same exact results. So I was wondering if I am missing some additional steps or if that is to be considered a bug.
For reference I used the code for trec text classification with graphsage_bi_fuse_dependency.yaml config. Basically I just did some changes to  the config file to use only a single worker and adapted the code slightly to run in colab.

**Comment by AlanSwift** [comment]
Thank you for pointing out the problem!
We are currently looking for possible bugs, please stay tuned!

**Comment by xiao03** [comment]
Close this issue due to inactivity. Please reopen it when necessary.
