### ISSUE TITLE
Kinship KG example

### ISSUE THREAD

**Issue by tomasonjo** [graph4ai/graph4nlp#419]
I am trying to run the Kinship KG example, but I find it confusing. The raw data contains test,train,and validate text files. If I run the kinship preprocess example:

`python examples/pytorch/kg_completion/kinship_main.py --data kinship --model ggnn_distmult --preprocess
`

I get the following error:

> FileNotFoundError: [Errno 2] No such file or directory: 'examples/pytorch/kg_completion/data/kinship/e1rel_to_e2_full.json'

Which is understandable as there is no file in there. Now I think, ok, so I must have already the preprocessed data as I have the train/test split, so I'll just run the second command:

`python examples/pytorch/kg_completion/kinship_main.py --data kinship --model ggnn_distmult
`

Now I get an error:

> AttributeError: 'StreamBatcher' object has no attribute 'loaders'

After a quick google search, I found that this is usually due to faulty preprocessing step, which I haven't completed anyway.

At the end of the day, I would like to add my own dataset in a form similar to the text,train,validate text files and train my own model. Any code examples would be greatly appreciated! I have been looking a bit at docs, but I am a PyTorch noob, so model definitions aren't helpful (yet) to me.

Thanks

**Comment by tomasonjo** [comment]
nevermind, there is also a `preprocess.sh` that could be added to https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/kg_completion readme

**Comment by Nicoleqwerty** [comment]
Thank you for your question. You can now run through the code, but don't know how to add new datasets? 
For bring your own data to KG completion, you must have the original files in the format of ``examples/pytorch/kg_completion/data/kinship/train.txt``, ``valid.txt`` and ``test.txt``, which a triple in a line is split by tab. Then, run ``python examples/pytorch/kg_completion/wrangle_KG.py YOURDATA`` to get the processed json files. This is included in the ``preprocess.sh`` file.
We will modify the readme in the next version to make it more readable.

**Comment by tomasonjo** [comment]
thank you very much, I'll give it a go!

**Comment by xiao03** [comment]
This issue is solved and will be closed. Please feel free to reopen this issue on any further questions.
