### ISSUE TITLE
More efficient BertEmbeddings 

### ISSUE THREAD

**Issue by j-rossi-nl** [graph4ai/graph4nlp#426]
## Motivation
I'm using a graph where each node holds a long text (up to 60k works). The current implementation of BertEmbeddings would only create Out-of-Memory issues.
* the inputs to the Bert model are not batched
* the mapping matrix cant be hold in memory
* the tokenization is done on the fly
* only BERT can be used, as it is hardcoded with `BertModel.from_pretrained(...)` 
* BertEmbeddings is using EVERY hidden state from EVERY layer of EVERY token
* 

## Pitch

I'm willing to pitch in a PR for a different BertEmbeddings class:
* processes raw text OR pre-processed texts (so we can split pre-processing and embedding)
* accepts any huggingface transformer model (so we can use lighter ones)
* split the text in chunks, and average the embeddings of the CLS token of each chunk

**Comment by AlanSwift** [comment]
Thank you for your interest and contribution. We will discuss it asap.

**Comment by xiao03** [comment]
Close this issue due to inactivity. Please reopen it when necessary.
