### ISSUE TITLE
Can we create a graph model for all of our contextual data and then use the same graph to train all our downstream models?

### ISSUE THREAD

**Issue by dbanka** [graph4ai/graph4nlp#428]
In the examples mentioned in the demo, we saw that graph construction was done while training the specific use case like classification. Is there a way, we can construct graph on whole of our contextual data and then use that graph for our downstream applications like classification, knowledge graph completion etc.?

**Comment by AlanSwift** [comment]
Do you mean that the graph construction component should be disentangled from the pipeline such that it can be used for other applications? Eg, after we trained the classification app with the dependency graph, we can use the same graph to train another app without constructing the graphs again?

**Comment by dbanka** [comment]
Yes exactly.

**Comment by AlanSwift** [comment]
OK. Currently, the processed graph data can be reused. You can just copy it to another project and load it to train another app. Do you encounter some problems?

**Comment by Nicoleqwerty** [comment]
@sandeepKondaveeti Hi, the graph used in KG Completion is a single ``graph4nlp.pytorch.data.dataGraphData`` object, while the ``data.pt`` file built by the ``graph_construction`` module is a dict object (in version 0.5) or a ``graph4nlp.pytorch.data.dataset.Dataset`` object (in version 0.4). I guess this leads to the **AttributeError**.

**Comment by sandeepKondaveeti** [comment]
@Nicoleqwerty , Please let us know if there is a way to covert the dict object to a single [graph4nlp.pytorch.data.dataGraphData](url). We want to use the same graph for multiple applications.

**Comment by Nicoleqwerty** [comment]
The dict is in the form of {'train': list of DataItems, 'test': list of DataItems, ...}. You can use DataItem.graph to access ``GraphData``.

**Comment by sandeepKondaveeti** [comment]
@Nicoleqwerty Even we try to access GraphData for all the values in the dict  DataItem.graph, we will be having multiple graphs, my query is how can we combine all of the dataitems to single graph.

**Comment by dbanka** [comment]
@Nicoleqwerty @AlanSwift 
What my thought was that we can convert all our data relationships to graph embedding model using graph construction. Then given any use case be it KG completion or classification, we have we can use the same graph. Lets say I have 10 different types of entities and 20 types of relationships between them. I wanted to put all of the data into graph model and then if I want to train a classification model using just 2 of those entity types, I can train a classification model taking the graph embedding from the graph model. Is my approach correct or am I missing something? Because I am unable to understand why should we construct separate graph for each of our use cases as shown in the examples.

**Comment by Nicoleqwerty** [comment]
@dbanka Hi, you can check the example codes of  KG completion and text classification. They are two completely different tasks with different inputs. For KG completion, the input is a single KG and the goal of KG completion is to predict the missing links between entity nodes. For text classification, each input is a (text, label) pair. A text classification dataset has lots of pairs. Unlike KG, there are usually no relation between texts in text classification. So we construct separate graph for each text. 

As for whether the constructed graph can be reused, I think take KG completion and KG node classification as a pair of examples is more suitable. Both tasks may take the same KG as input. You can certainly do KG completion or node classification on the same graph.

**Comment by xiao03** [comment]
Close this issue due to inactivity from the user. Please reopen it when necessary.
