### ISSUE TITLE
[Roadmap] Graph4NLP v0.5.2 plan

### ISSUE THREAD

**Issue by AlanSwift** [graph4ai/graph4nlp#429]
Task List
* [New Feature] Develop the inference wrapper: InferenceWrapper. Users can easily generate results by the wrapper with raw inputs. For example:
```
model = load_model(...)
wrapper = InferenceWrapper(model, ....)
wrapper.predict(["Hello world"])
```
* [Feature] Develop StandfordNLP and tokenize template parameters.
* [Feature] Separate Graph topology and graph embeddings.

**Comment by nashid** [comment]
@AlanSwift when these features will be delivered? Any ETA?

**Comment by AlanSwift** [comment]
> @AlanSwift when these features will be delivered? Any ETA?

Yes, please check 0.5.5.

**Comment by AlanSwift** [comment]
This issue is closed.
