### ISSUE TITLE
StanfordCoreNLP Freezes

### ISSUE THREAD

**Issue by LucasAPayne** [graph4ai/graph4nlp#430]
## ❓ Questions and Help

I have a sentiment analyzer project that is very similar to the text classifier example. I trained it on the IMDb dataset that is provided by torchtext. It has 50,000 total movie reviews, and it is about 40 MB in size after I trim it down to about 35,000 reviews for a better split ratio. From the dataset, I created `train.txt`, `test.txt`, and `val.txt` and formatted the reviews to be used as a `Text2LabelDataset`. I use this command to run StanfordCoreNLP, and the arguments match the ones in the instantiation of my class `IMDBDataset` that inherits from `Text2LabelDataset`.

`java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 50000`

The main issues that I run into are that StanfordCoreNLP takes nearly an entire day to process the whole dataset, and after running for a few hours, it will freeze and stop working. At that point, I can press `Ctrl+C` on the command prompt and run the command again for it to resume. StanfordCoreNLP also returns several TimeoutExceptions and OutOfMemoryErrors (they are not fatal errors). I started with a timeout of 15,000 and increased to 50,000, but I still get several timeouts. Also, I tried allocating more memory to StanfordCoreNLP all the way up to 16 GB, but I still get OutOfMemoryExceptions.

In order to make StanfordCoreNLP run without freezing, I reduced my dataset to 7,000 total reviews, and I limited each review to be about 100 words. However, I would like to make use of the whole dataset without having to monitor the preprocessing step, and this issue also concerns me for future projects.

I am not sure if this issue is on Graph4NLP's side or with StanfordCoreNLP, but I thought I would start here. My main questions are these:
- Could the performance of StanfordCoreNLP be improved without sacrificing most of the data?
- Are there other options besides StanfordCoreNLP to process data for Graph4NLP?
- What could cause the OutOfMemoryError and TimeoutException?

I can provide my code or the specific errors if needed.

**Comment by AlanSwift** [comment]
We are sorry for the inconvenience.
Could you provide your code (including data) and the error traceback?
In addition, could you give us your machine's information such as memory size? (I suggest you use the `top` command to monitor your memory usage and tell me the memory usage (e.g., graph4nlp memory usage: xx%, stanfordcorenlp memory usage: xx%) when the code crashes if possible.)
