### ISSUE TITLE
Facing an issue while creating an Inference for KGC using our dataset

### ISSUE THREAD

**Issue by sandeepKondaveeti** [graph4ai/graph4nlp#439]
I am trying to create an inference for KGC and also saving the graph_embeddings, In the process I have done the relevant data formatting and creation of json files using [wrangle_KG.py](https://github.com/graph4ai/graph4nlp/blob/9e0de1d594d8b020bbfb53488dfaf1bb14b3b780/examples/pytorch/kg_completion/wrangle_KG.py), I have pre-processed the data to generate /home/~user/.data/{dataset} and the process is successful, Now I have run the dataset_main.py file to train with a specific batch_size and epoch and the operation is successful and was able to save the model to saved_models folder. For Inference part with new test_data tried generating the new /home/~user/.data/{dataset}/test_ranking folder and tried running the model for which I am running to Shape related issues at Line 1204 func **load_state_dict** state_dict['emb_e.weight'] module.py file of torch.nn.modules.

Please let me know whether process followed for the inference of KGC is correct, if not guide me to implement the same.

**Comment by Nicoleqwerty** [comment]
Hi, you need add "--resume" to your cmd to load the saved model. We will add a separate "inference.py" document in the next version.

**Comment by xiao03** [comment]
This issue is closed due to no comments for over two weeks. Please re-open it if needed.
