### ISSUE TITLE
stanfordcorenlp

### ISSUE THREAD

**Issue by mhillebrand** [graph4ai/graph4nlp#449]
I had to change every instance of `stanfordcorenlp.StanfordCoreNLP` to `stanfordcorenlp.corenlp.StanfordCoreNLP` in the graph4nlp code. I should point out that I have [Lynten/stanford-corenlp](https://github.com/Lynten/stanford-corenlp) v3.9.1.1, installed via `pip install stanfordcorenlp`. Is this not the Python client you guys use for the StanfordCoreNLP Java server? Or perhaps I'm using a different version than you? The latter sounds difficult to imagine since this Lynten library's last release was from 2018.

It sounds like everyone now prefers the [stanza](https://github.com/stanfordnlp/stanza) library for connecting Python clients to a StanfordCoreNLP server.

**Comment by AlanSwift** [comment]
Sorry for the late reply.
We install the Stanford CoreNLP by the command ``pip install stanfordcorenlp`` and the source link is [https://pypi.org/project/stanfordcorenlp/](https://pypi.org/project/stanfordcorenlp/).
I have checked and it is ``from stanfordcorenlp import StanfordCoreNLP``.  (You can also see the ``Simple usage`` in the github repo [https://github.com/Lynten/stanford-corenlp](https://github.com/Lynten/stanford-corenlp)).

``stanza`` is a good suggestion. We will discuss it.

**Comment by mhillebrand** [comment]
Strange. I uninstalled stanfordcorenlp and reinstalled it. Now everything works fine.
