### ISSUE TITLE
Process getting killed while running the text summarization example

### ISSUE THREAD

**Issue by mjzohrabi** [graph4ai/graph4nlp#452]
## ❓ Questions and Help

I'm trying to run the summarization example (ideally by running it on the full dataset and then trying other models and parameters), But each time the process gets 'killed'. Is there a way to run it properly without changing the default parameters? 
I'm using a system with 16 virtual cores for CPU, 32 GB RAM, and RTX 2080 Ti GPU. 
If I need to upgrade my system please let me know, too.

**Comment by AlanSwift** [comment]
Can you provide the error tracebacks and the system information?

**Comment by mjzohrabi** [comment]
I Have run the model without GPU, or by using Glove 100d and changing the embedding dimensions. So I concluded that the problem is my GPU memory. The problem occurred in the building vocab phase, using the aforementioned modifications solved the problem. 

Thanks.

**Comment by xiao03** [comment]
The issue is closed. Please reopen it if necessary.
