### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by mhillebrand** [graph4ai/graph4nlp#456]
## 🚀 Feature
Training on multiple GPUs

## Motivation

I'd like to train a graph classifier using millions of training examples, and I have more than one GPU. A quick, project-wide search for "DataParallel" yielded no results, though. Is this on the roadmap? Thanks!

**Comment by AlanSwift** [comment]
Currently, it is not on our roadmap since we think this is an application-side feature.
However, do you encounter some difficulties?

**Comment by mhillebrand** [comment]
Ah, okay. I'll bake that multi-gpu stuff into my code then. Thanks.

**Comment by nashid** [comment]
@mhillebrand how do you solve the multi-GPU issue?

**Comment by mhillebrand** [comment]
@nashid I never made it that far. I realized that a DistilBERT classifier yielded higher accuracy in less time for my particular use case, so I removed Graph4NLP from my current project. I'm hoping to make use of it in future projects, though.
