### ISSUE TITLE
Build custom dataset for regression problem

### ISSUE THREAD

**Issue by biggytruck** [graph4ai/graph4nlp#461]
Hi,

As mentioned in #351 , it's possible to build a GNN-based regression model by replacing the CE with MSE loss in the text classification example. But how should I build the dataset? In the text classification example, `TrecDataset` inherits from `Text2LabelDataset` which builds its own label model using `LabelModel`. As I traced back to the source code, it seems `LabelModel` is specifically designed for discrete label as it needs to compute the number of classes in the label set. Can I build my dataset in a similar way that `TrecDataset` was implemented? If not, how should I implement a dataset for regression problems? Any code example would be highly appreciated. Thanks in advance.

**Comment by hugochan** [comment]
> Hi,
> 
> As mentioned in #351 , it's possible to build a GNN-based regression model by replacing the CE with MSE loss in the text classification example. But how should I build the dataset? In the text classification example, `TrecDataset` inherits from `Text2LabelDataset` which builds its own label model using `LabelModel`. As I traced back to the source code, it seems `LabelModel` is specifically designed for discrete label as it needs to compute the number of classes in the label set. Can I build my dataset in a similar way that `TrecDataset` was implemented? If not, how should I implement a dataset for regression problems? Any code example would be highly appreciated. Thanks in advance.

@biggytruck Thank you for your interest to our library! Yes, you can build your own dataset class for the regression task. You may notice that `TrecDataset` inherits from `Text2LabelDataset` class. Similarly, you will need to first build your own `Text2NumberDataset` class following `Text2LabelDataset`, and then build your high-level dataset class which inherits from  `Text2NumberDataset`.

**Comment by biggytruck** [comment]
Thanks for your reply. I have implemented my `Text2NumberDataset` as you suggested. Would the team consider adding this support for continuous labels in a future release?

**Comment by hugochan** [comment]
> Thanks for your reply. I have implemented my `Text2NumberDataset` as you suggested. Would the team consider adding this support for continuous labels in a future release?

@biggytruck Can you tell us what your application is? You are welcome to contribute to the library if you think your use case is interesting and beneficial to other people.

**Comment by xiao03** [comment]
This issue is closed due to inactivity. Please reopen it when necessary.
