### ISSUE TITLE
Text summarization example test part error

### ISSUE THREAD

**Issue by mjzohrabi** [graph4ai/graph4nlp#462]
## ❓ Questions and Help

Hi, while running the text summarization example the model checkpoint is saved ('config.json,  metric.log, params.saved' are inside the gcn_bi_fuse_l2_ckpt folder) but I get the following error for the test part: AttributeError: 'EarlyStopping' object has no attribute 'load_checkpoint'. 
![546](https://user-images.githubusercontent.com/56761646/143781963-f669cdcc-bf64-4abe-8434-a08079cc1dbe.JPG)

**Comment by AlanSwift** [comment]
Sorry for the late reply. This is a bug during the code migration. Thank you for your report. We will fix it in the next version.
@Nicoleqwerty Please fix it.

**Comment by Nicoleqwerty** [comment]
Hi @mjzohrabi, You can fix it line 444 in main.py to ''self.model.load_checkpoint(self.stopper.save_model_path)''. We will fix it in next version.

**Comment by mjzohrabi** [comment]
Thanks a lot @AlanSwift  @Nicoleqwerty.

**Comment by AlanSwift** [comment]
This issue will be closed.
