### ISSUE TITLE
How to use the Graph2Seq model?

### ISSUE THREAD

**Issue by vbayubaskoro** [graph4ai/graph4nlp#463]
## ❓ Questions and Help
Hi!

I'm working on a project where I want to feed custom dataset to the Graph2Seq model. Before I do that, I just want to experiment a little bit with a super simple graph data (one graph of 4 nodes with 4 edges) to make sure I understand the workflow. My understanding is that I need to convert my graph to a DataItem -> DataSet -> which can then be fed to a model. I am a little bit stuck on the step from DataSet to fitting Graph2Seq model.

Thanks!

**Comment by vbayubaskoro** [comment]
This is what I've done so far: 

I created a graph g and added some nodes  and some edges. I then constructed a Text2TextDataItem where I used the extract method. I changed the implementation of extract() so that it takes in my graph. Once I have the input and output tokens from the extract() method, I constructed a Text2TextDataSet. Here, I used the vectorization() and collate_fn() methods on my previous outputs. 

I am following this:https://graph4ai.github.io/graph4nlp/guide/dataset/customize.html

What should my next step be after customizing batching if I want to feed my simple graph to Graph2Seq model?

**Comment by AlanSwift** [comment]
After finishing vectorization, you can feed the batch graphdata to ``Graph2Seq`` model.
An example is: [https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/examples/pytorch/semantic_parsing/graph2seq/main.py#L227](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/examples/pytorch/semantic_parsing/graph2seq/main.py#L227).
If you meet some bugs in this step and don't know the solution, you can attach your codes.

**Comment by xiao03** [comment]
The issue is closed due to inactivity. Please reopen it when necessary.
