### ISSUE TITLE
Is there a limitation on how large a graph can graph4nlp handle?

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#466]
## ❓ Questions and Help

Currently, I am using the [NMT](https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/nmt ) example using Graph2Seq model for a translation task. In my case, I have a large graph with many nodes and edges.

I would be curious to know whether there were any experiments with graph4nlp on large graphs. Were there any experiments regarding how large graph graph4nlp can handle effectively?

**Comment by AlanSwift** [comment]
The backend of Graph4NLP is ["DGL"](https://www.dgl.ai/). Thus for this part, please refer to DGL scaleability. As for other parts such as the decoder, it is hard to give a certain limitation.

**Comment by nashid** [comment]
For my case, the input to the Graph2Seq is a large graph (with a mean of 2000 nodes in the dataset) but the output sequence is relatively small with around 15 tokens.

**Comment by AlanSwift** [comment]
OK. I think you should try a small batch_size for a single GPU.

**Comment by nashid** [comment]
Thanks a lot for your insight. Closing the task.

**Comment by nashid** [comment]
@AlanSwift how I can select multiple GPU for the `Graph2Seq` model while feeding a large graph.
