### ISSUE TITLE
Customizing dataset 

### ISSUE THREAD

**Issue by icocoder** [graph4ai/graph4nlp#467]
## ❓ Questions and Help
Hi, I have created a graph from my own text dataset with DGL. 
I wanted to ask what is the easiest way to use it (can I use it directly)?

**Comment by nashid** [comment]
@icocoder you can have a look here https://graph4ai.github.io/graph4nlp/guide/graphdata/construct.html#importing-from-other-sources

You can import data from other sources. 

Look into the `GraphData` import API like `from_dgl()`.

**Comment by icocoder** [comment]
@nashid 
It's great, I didn't know about it. Thanks for your help.

**Comment by AlanSwift** [comment]
@icocoder @nashid Thanks a lot for your reply. I just missed it.

**Comment by nashid** [comment]
@firqaaa to the best of my knowledge we can only import from 

```
from_dgl(), from_dense_adj(), from_scipy_sparse_matrix() and from_graphdata()
```

Link: https://graph4ai.github.io/graph4nlp/guide/graphdata/construct.html#importing-from-other-sources

**Comment by LN-Curiosity** [comment]
> @firqaaa to the best of my knowledge we can only import from
> 
> ```
> from_dgl(), from_dense_adj(), from_scipy_sparse_matrix() and from_graphdata()
> ```
> 
> Link: https://graph4ai.github.io/graph4nlp/guide/graphdata/construct.html#importing-from-other-sources
Hi, nashid. @nashid 
I have a question about it.
when constructing a graphdata obj, only providing node feat is valid? 

**This is my error log:**

`Traceback (most recent call last):
  File "/opt/graph4nlp/examples/pytorch/semantic_parsing/graph2seq/Demo.py", line 48, in <module>
    seq_out, _, _ = graph2seq(batch_graph=batch_graph, tgt_seq=tgt_seq)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/graph4nlp/graph4nlp/pytorch/models/graph2seq.py", line 228, in forward
    batch_graph = self.graph_initializer(batch_graph)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/graph4nlp/graph4nlp/pytorch/modules/graph_embedding_initialization/graph_embedding_initialization.py", line 38, in forward
    return self.embedding_layer(graph_data)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/graph4nlp/graph4nlp/pytorch/modules/graph_embedding_initialization/embedding_construction.py", line 247, in forward
    token_ids = batch_gd.batch_node_features["token_id"]
  File "/opt/graph4nlp/graph4nlp/pytorch/data/views.py", line 147, in __getitem__
    return self._graph._get_batch_node_features(item)
  File "/opt/graph4nlp/graph4nlp/pytorch/data/data.py", line 947, in _get_batch_node_features
    raise Exception("Node feature {} doesn't exist!".format(item))
Exception: Node feature token_id doesn't exist!

Process finished with exit code 1
`

**My code:**

`opt = get_basic_args(graph_construction_name="node_emb", graph_embedding_name="gat", decoder_name="stdrnn")
opt["graph_embedding_name"] = "gat"
opt["graph_construction_name"] = "custom"
vocab = torch.load("/opt/graph4nlp/examples/pytorch/semantic_parsing/graph2seq/jobs/processed/DependencyGraph/vocab.pt")
graph2seq = Graph2Seq.from_args(opt=opt, vocab_model=vocab)
batch_graph = []
g1 = dgl.graph(([0, 1], [1, 2]))
g1.ndata['node_feat'] = torch.randn((3, 300))
print(g1)
g1 = from_dgl(g1)
g2 = dgl.graph(([0, 1], [2, 3]))
g2.ndata['node_feat'] = torch.randn((4, 300))
print(g2)
g2 = from_dgl(g2)
batch_graph.append(g1)
batch_graph.append(g2)
batch_graph = to_batch(batch_graph)

tgt_seq = torch.Tensor([[1, 2, 3], [4, 5, 6]])
seq_out, _, _ = graph2seq(batch_graph=batch_graph, tgt_seq=tgt_seq)
print(seq_out.shape)`

**Comment by LN-Curiosity** [comment]
Looking forward to your reply, thanks. @nashid @AlanSwift
