### ISSUE TITLE
Summarization example

### ISSUE THREAD

**Issue by mjzohrabi** [graph4ai/graph4nlp#469]
## ❓ Questions and Help

Hi, in the summarization example, I want to try other graph neural networks (replacing GCN with GraphSAGE, GAT, ...) 
How can I do it with minimal change to the original code?

**Comment by AlanSwift** [comment]
You just need to modify the parameters in the [configure file](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/examples/pytorch/summarization/cnn/config/gcn_bifuse.yaml#L2).
For example, GCN --> GAT.
You first need to modify L2: "gat". Then you need to modify ``graph_embedding_args`` in L40-L54. You can refer to the default GAT parameters in [this file](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/config/graph_embedding/gat.yaml).

**Comment by AlanSwift** [comment]
We plan to make it more clear in the documentation.

**Comment by icocoder** [comment]
This is great, Thanks a lot.

**Comment by icocoder** [comment]
I have one more question, for using other graph embeddings which currently aren't included in the graph_embedding directory such as GTN (Graph Transformer Networks), how can I do it?
Is there any priority between using DGL or PyG libraries?

**Comment by AlanSwift** [comment]
You can implement it. Since our backend is DGL, the most straightforward way is to convert the ``GraphData`` to ``DGLGraph`` and do the GNN by calling DGL's implementation. Then you can convert the computation results to ``GraphData`` and do the downstream tasks.
Notes: You can refer to the GAT implementation ([code](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_embedding/gat.py#L147)).

**Comment by icocoder** [comment]
@AlanSwift  Thank you very much.

**Comment by mjzohrabi** [comment]
@AlanSwift 
I changed the config file, but after running the model this error occurred: 
![Capture](https://user-images.githubusercontent.com/56761646/145456502-2ad48891-2e75-4971-bc06-b4778842d259.JPG)

Here I tried to use gat. The config yaml file changed like this: 
[gatconf.txt](https://github.com/graph4ai/graph4nlp/files/7687656/gatconf.txt)

**Comment by AlanSwift** [comment]
I think you should set ``allow_zero_in_degree`` to be ``True``.

**Comment by mjzohrabi** [comment]
This solution worked and the model was run completely. 
But about the other recommended solution (adding self-loop to nodes), may I ask how can do that?

**Comment by AlanSwift** [comment]
The self-loop is missed during the migration. We will fix it now.
Currently, you can add the self-loop by adding the following code in [this Line](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_embedding/gat.py#L162):
```
dgl_graph = dgl.add_self_loop(dgl_graph)
```

**Comment by mjzohrabi** [comment]
The problem is solved. Thanks again.
