### ISSUE TITLE
Multi-head attention

### ISSUE THREAD

**Issue by icocoder** [graph4ai/graph4nlp#479]
## ❓ Questions and Help

Hello, I want to change the multi head attention module (by using different attentions for different heads) but I couldn't find where is it implemented either in graph4nlp or DGL libraries. It is mentioned in the following tutorial [DGL tutorial on GAT](https://graph4ai.github.io/graph4nlp/guide/gnn/gat.html?highlight=gat) and it is used in the configuration part of graph4nlp examples, but as I mentioned I couldn't find where this part of code is implemented. 

Thanks in advance.

**Comment by AlanSwift** [comment]
Hi!
The GAT is implemented by DGL.[https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_embedding/gat.py#L5](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_embedding/gat.py#L5)

A link to DGL is [https://github.com/dmlc/dgl/blob/42897c3652cabd931d856b298b809ff379201683/python/dgl/nn/pytorch/conv/gatconv.py#L154](https://github.com/dmlc/dgl/blob/42897c3652cabd931d856b298b809ff379201683/python/dgl/nn/pytorch/conv/gatconv.py#L154).

If you want to customize this part, you can replace the [GATConv](https://github.com/graph4ai/graph4nlp/blob/7690b54eff4194ea0627be82a5f6316e19caddfa/graph4nlp/pytorch/modules/graph_embedding/gat.py#L5) by your implementation.

**Comment by icocoder** [comment]
@AlanSwift Thanks a lot.
