### ISSUE TITLE
Co-occurrence graph construction

### ISSUE THREAD

**Issue by icocoder** [graph4ai/graph4nlp#480]
## ❓ Questions and Help

Hello, I wanted to ask how can I use the following kind of graph construction (I have searched for it but I couldn't find the implementation or API in the library)
![co-occurrence](https://user-images.githubusercontent.com/94281906/147872584-95777391-0307-4407-8766-60b86ffd6d4d.JPG)

**Comment by icocoder** [comment]
To make my question more clear, I'm trying to learn how to use different construction methods on the summarization example. 
I the last two days I have tried to use another construction method such as 'node embedding based' and based on other examples, but there isn't any straightforward section in the docs to learn about these things. 
I don't know if I'm learning based on the right path or not, currently I'm just focusing on this one example (summarization example) and I'm trying to run and reconfigure it. So now I have these two questions: 

1. How can I use other construction methods (they are implemented in the code but I didn't really understand how can I change the config file properly, so every time I got errors (specifically I tried 'NodeEmbeddingBasedGraphConstruction')

2. If there is other recommended ways to learn about how to use the library for a specific task (except learning by running one example in different ways and trying to reconfigure it) , please explain the learning path.

**Comment by AlanSwift** [comment]
This graph is not officially implemented. Perhaps you have to implement it by yourself.

**Comment by icocoder** [comment]
I'm currently working on the text summarization example, can you please tell me which part of codes in the graph construction code should be changed?

**Comment by AlanSwift** [comment]
I think you should implement the CoOccurrenceGraph in [graph construction module](https://github.com/graph4ai/graph4nlp/tree/master/graph4nlp/pytorch/modules/graph_construction).

**Comment by icocoder** [comment]
Thanks a lot, I'll try to implement it.
