### ISSUE TITLE
How to use multiple encoders for the Graph2Seq model?

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#488]
How can I use multiple encoders for the Graph2Seq model? Is there any example of that?

**Comment by AlanSwift** [comment]
Can you explain more specifically? I can't get "multiple encoders".

**Comment by nashid** [comment]
As an example, from OpenNMT: 

- [[Multiple sources with multiple features](https://forum.opennmt.net/t/multiple-sources-with-multiple-features/3590)](https://forum.opennmt.net/t/multiple-sources-with-multiple-features/3590)
