### ISSUE TITLE
copy mechanism does not work for the NMT model

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#492]
## 🐛 Bug

I was attempting to use copy-mechanism for the NMT model. But I get the following error when I set the copy mechanism flag. 

```
Copy is not fit to NMT 
```

## To Reproduce

1. NMT example: https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/nmt/config/dynamic_gcn.yaml#L66
2. Set copy mechanism to true `use_copy: true`
3. Error: `Copy is not fit to NMT `

## Expected behaviour

I expect to use the copy mechanism for the Graph2Seq model.

By the way, I see this in the code:

```
assert self.use_copy is False, print("Copy is not fit to NMT")
```

So copy mechanism is not supported for the Graph2Seq model?

**Comment by AlanSwift** [comment]
Copy mechanism is used to "copy" the input sequence's distribution to the output. Currently, we just give a feasible implementation of NMT. In this version, the source corpus and the target corpus have different vocabularies. So the copy mechanism is not suitable. You can explore it!

**Comment by nashid** [comment]
@AlanSwift In my case, the input and output use the same vocabulary. That's why I want to try out the copy mechanism.
