### ISSUE TITLE
Model keep generating UNK tokens

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#499]
## 🐛 Bug

The model is generating too many UNK tokens.

## To Reproduce
Set limited vocabulary:

```
    top_word_vocab: 10000
    min_word_freq: 5
``` 

## Expected behavior

For the NLP example, as I am using limited vocab size, I am expecting to see UNK tokens. But now in most cases, I see series ok UNK tokens coming up. 

A couple of examples:

```
[theme.breakpoints.up('md')]: {,"}, { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> { <unk> {"
pagesize:5,"<unk> : <unk> , <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>"
"name: ""dan mitchell"",",$( <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>
```

## Environment

 - Graph4NLP Version (e.g., 0.4.1): 0.4.1
 - Backend Library & Version (e.g., PyTorch 1.6.0): PyTorch
 - OS (e.g., Linux): Ubuntu
 - How you installed Graph4NLP (`pip`, source): source
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): 11.0
 - GPU models and configuration (e.g. 2080Ti): T4

**Comment by hugochan** [comment]
@nashid thanks for reporting this issue! Can you please share more context (e.g., which task/dataset/model setting?) to help us reproduce the issue?

**Comment by spwidodo** [comment]
HI..
There is solution for this bug ?

Thanks....
