### ISSUE TITLE
bug report related to BertEmbedding and pytorch/test/

### ISSUE THREAD

**Issue by WuXuan374** [graph4ai/graph4nlp#500]
## 🐛 Bug

Some code bugs in pytorch/test/ folder and BertEmbedding part

## Background
Great library and many thanks!
I need to mock some source code so that this library can fit into my application. 
When reading and running some source code, I encountered some problems. Below is some examples and my solutions to them.

## pytorch/test/

Take pytorch/test/graph_construction/run_batch_graph_embedding_construction.py as example. 

- L26 'pretrained_word_emb_file' should be replaced with 'pretrained_word_emb_name'
- L44 and L48, there's no 'word_vocab' in vocab_model, in_word_vocab and out_word_vocab instead
- L47: graph.node_attributes[j]["token_idx"]. In practical, it should be "token_id" so that model can run successfully
           
## graph_embedding_initialization/embedding_construction.py/BertEmbedding
- L493-L499: raising an error when setting "output_hidden_states=True, return_dict=True" in self.bert_model; following modification would work for me
```python
self.bert_config = BertConfig.from_pretrained(name, output_hidden_states=True, return_dict=True)
self.bert_model = BertModel.from_pretrained(name, config=self.bert_config)
```

## Conclusion

problems in pytorch/tests/: tiny bugs. Mostly wrong argument names(maybe from previous version).
I think you may need to update this folder'code, since they are useful in learning how a graph is constructed

problems in BertEmbedding: I guess different version of 'transformers' leads to them.

## Pull request if needed
If you need a pull request about above fix, I'm willing to.

## Environment

 - Graph4NLP Version (e.g., 0.5.5):
 - Backend Library & Version (e.g., PyTorch 1.10.1):
 - OS : Linux
-  transformers              2.1.1

**Comment by hugochan** [comment]
Hi @WuXuan374 , thanks for your interest to the library and reporting the issues about the test examples under the `pytorch/test` folder! The folder contains all our unit test examples which are currently under construction and might not be compatible with the latest library APIs. Yes, you're very welcome to send a PR to help us improve them.
