### ISSUE TITLE
"Connecting to stanfordcorenlp server..." for a long time and there is no response

### ISSUE THREAD

**Issue by crazyseabiscuit** [graph4ai/graph4nlp#513]
## To Reproduce

1.  install according to https://github.com/graph4ai/graph4nlp
excute the following code 
from graph4nlp.pytorch.datasets.jobs import JobsDataset
from graph4nlp.pytorch.modules.graph_construction.dependency_graph_construction import DependencyBasedGraphConstruction
from graph4nlp.pytorch.modules.config import get_basic_args
from graph4nlp.pytorch.models.graph2seq import Graph2Seq
from graph4nlp.pytorch.modules.utils.config_utils import update_values, get_yaml_config

jobs_dataset = JobsDataset(root_dir='graph4nlp/pytorch/test/dataset/jobs',
                           topology_builder=DependencyBasedGraphConstruction,
                           graph_name="topology_builder",
                           topology_subdir='DependencyGraph')  # You should run stanfordcorenlp at background

it show "Connecting to stanfordcorenlp server..." for a long time and there is no response
## Expected behavior

the program can be excuted 

## Environment

Windows 11
Cuda 10.1 
graph4nlp-cu101                    0.5.5
*************************************************************************************************
Btw I also try to install in my Mac, it throws a different error:
"No module named 'stanfordcorenlp'"

Not sure it is the same issue from my windows environment

**Comment by nashid** [comment]
From tutorial:

If no processed data is available (if there is no `data/processed` directory from the root directory of the repository or it is empty), open a separate command prompt and run these commands to initialize an instance of StanfordCoreNLP to process the data:
Download from https://huggingface.co/stanfordnlp/CoreNLP/blob/main/stanford-corenlp-latest.zip.

```
cd path_to_stanfordcorenlp
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000
```

Check steps from the tutorial:
https://graph4ai.github.io/graph4nlp/tutorial/math_word_problem.html

**Comment by crazyseabiscuit** [comment]
thanks for the response , it worked for me now

**Comment by Anshita1Saxena** [comment]
Thanks for the response, it worked for me too...
