### ISSUE TITLE
named entity recognition - no readme

### ISSUE THREAD

**Issue by vinven7** [graph4ai/graph4nlp#517]
## 📚 Documentation

There is no readme file for the named entity recognition example. I'm not sure how to implement this

**Comment by nashid** [comment]
I have not run the example https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/name_entity_recognition

But don't think it would be much different than running other examples.

```
Requirements
    pip install tensorboard

How to run

Start the StanfordCoreNLP server for data preprocessing:
- Download StanfordCoreNLP https://stanfordnlp.github.io/CoreNLP/
- Go to the root folder and start the server:
    java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000

run script
- python main.py --name test
```

**Comment by vinven7** [comment]
Thank you! I will try this out. Where can I learn how to convert a list of annotated text files into the format required for the example?

**Comment by nashid** [comment]
Dataset customization: https://graph4ai.github.io/graph4nlp/guide/dataset/customize.html#guide-customize

**Comment by hugochan** [comment]
@xguo7 Can you please add a readme to the NER example?

**Comment by nashid** [comment]
@vinven7 what do you mean? You want to see number of edges and number of nodes in a graph?

**Comment by xguo7** [comment]
The readme of NER example has been added.
