### ISSUE TITLE
text classification example error 

### ISSUE THREAD

**Issue by vinven7** [graph4ai/graph4nlp#518]
In running the text classification example:

`python -m examples.pytorch.text_classification.run_text_classifier -config examples/pytorch/text_classification/config/trec/gat_bi_fuse_constituency.yaml  `

It runs for a bit until the code crashes at a 'deepcopy' error:

`.vector_cache/glove.840B.300d.zip: 2.18GB [07:03, 5.13MB/s]                                                                                                             100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 2196016/2196017 [02:29<00:00, 14664.29it/s]Pretrained word embeddings hit ratio: 0.9563318777292577                                                                                                                Using pretrained word embeddings                                                                                                                                        [ Initialized word embeddings: (8702, 300) ]                                                                                                                            Saving vocab model to examples/pytorch/text_classification/data/trec/processed/constituency_graph/vocab.pt                                                              Saving label mappings to examples/pytorch/text_classification/data/trec/processed/constituency_graph/label.pt                                                           Traceback (most recent call last):                                                                                                                                        File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                             "__main__", mod_spec)                                                                                                                                                 File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/runpy.py", line 85, in _run_code                                                                        exec(code, run_globals)                                                                                                                                               File "/home/jupyter/Vineeth/graph4nlp/examples/pytorch/text_classification/run_text_classifier.py", line 537, in <module>                                                 main(config)                                                                                                                                                          File "/home/jupyter/Vineeth/graph4nlp/examples/pytorch/text_classification/run_text_classifier.py", line 445, in main                                                     runner = ModelHandler(config)                                                                                                                                         File "/home/jupyter/Vineeth/graph4nlp/examples/pytorch/text_classification/run_text_classifier.py", line 227, in __init__                                                 self._build_dataloader()                                                                                                                                              File "/home/jupyter/Vineeth/graph4nlp/examples/pytorch/text_classification/run_text_classifier.py", line 267, in _build_dataloader                                        reused_label_model=None,                                                                                                                                              File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/datasets/trec.py", line 59, in __init__                                                                           **kwargs                                                                                                                                                              File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/data/dataset.py", line 1390, in __init__                                                                          **kwargs,                                                                                                                                                             File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/data/dataset.py", line 414, in __init__                                                                           self._process()                                                                                                                                                       File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/data/dataset.py", line 813, in _process                                                                           self.vectorization(self.train)                                                                                                                                        File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/data/dataset.py", line 1505, in vectorization                                                                     data_items[idx], self.vocab_model, label_model=self.label_model, use_ie=use_ie                                                                                        File "/home/jupyter/Vineeth/graph4nlp/graph4nlp/pytorch/data/dataset.py", line 1460, in _vectorize_one_dataitem                                                           item = deepcopy(data_item)                                                                                                                                            File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 180, in deepcopy                                                                         y = _reconstruct(x, memo, *rv)                                                                                                                                        File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 280, in _reconstruct                                                                     state = deepcopy(state, memo)                                                                                                                                         File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 150, in deepcopy                                                                         y = copier(x, memo)                                                                                                                                                   File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                                                   y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                                        File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 150, in deepcopy                                                                         y = copier(x, memo)                                                                                                                                                   File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 247, in _deepcopy_method                                                                 return type(x)(x.__func__, deepcopy(x.__self__, memo))                                                                                                                File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 180, in deepcopy                                                                         y = _reconstruct(x, memo, *rv)                                                                                                                                        File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 280, in _reconstruct                                                                     state = deepcopy(state, memo)                                                                                                                                         File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 150, in deepcopy                                                                         y = copier(x, memo)                                                                                                                                                   File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 240, in _deepcopy_dict                                                                   y[deepcopy(key, memo)] = deepcopy(value, memo)                                                                                                                        File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/copy.py", line 161, in deepcopy                                                                         y = copier(memo)                                                                                                                                                    TypeError: cannot deepcopy this pattern object  `

**Comment by hugochan** [comment]
@vinven7 Thanks for reporting the issue! We will take a look into this and keep you posted.

**Comment by hugochan** [comment]
Hi @vinven7, sorry for the late reply! I was not able to reproduce the error. Can you tell me which library version you were using? Because the error was raised by `item = deepcopy(data_item)`, can you print out the data_item? Another thing to try is maybe you can delete the `data/trec/processed/constituency_graph` folder and rerun the code.
