### ISSUE TITLE
name_entity_recognition

### ISSUE THREAD

**Issue by vinven7** [graph4ai/graph4nlp#519]
When I run 

` python examples/pytorch/name_entity_recognition/main.py`

i get the error:

`starting build the dataset                                                                                              Traceback (most recent call last):                                                                                        File "examples/pytorch/name_entity_recognition/main.py", line 391, in <module>                                            runner = Conll()                                                                                                      File "examples/pytorch/name_entity_recognition/main.py", line 107, in __init__                                            self.build_dataloader()                                                                                               File "examples/pytorch/name_entity_recognition/main.py", line 125, in build_dataloader                                    tag_types= self.tag_types,                                                                                            File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/typing.py", line 1231, in __new__                       return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)                                                          File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/typing.py", line 1186, in _generic_new                  return base_cls.__new__(cls)                                                                                        TypeError: Can't instantiate abstract class ConllDataset with abstract methods download  `

**Comment by vinven7** [comment]
This seems to be a problem with the ConllDataset:

`TypeError                                 Traceback (most recent call last)
<ipython-input-9-058c9c65c445> in <module>
----> 1 dataset = ConllDataset()

~/anaconda3/envs/vineeth/lib/python3.6/typing.py in __new__(cls, *args, **kwds)
   1229             raise TypeError("Type Generic cannot be instantiated; "
   1230                             "it can be used only as a base class")
-> 1231         return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
   1232 
   1233 

~/anaconda3/envs/vineeth/lib/python3.6/typing.py in _generic_new(base_cls, cls, *args, **kwds)
   1184         if (base_cls.__new__ is object.__new__ and
   1185                 cls.__init__ is not object.__init__):
-> 1186             return base_cls.__new__(cls)
   1187         else:
   1188             return base_cls.__new__(cls, *args, **kwds)

TypeError: Can't instantiate abstract class ConllDataset with abstract methods download`

**Comment by SaizhuoWang** [comment]
Thanks for reporting this issue. We will look into this. 

Currently, a quick fix is to uncomment L221-L224 in `examples/pytorch/name_entity_recognition/conll.py` to implement the `download()` method. But this requires you to make sure that the raw Conll dataset is present, i.e. the `conll/raw` dir in the NER example directory and the corresponding files are present. 

We will be working on a more thorough fix.

**Comment by vinven7** [comment]
@SaizhuoWang Thank you! This function is not being executed. I'm getting the same error as before

**Comment by SaizhuoWang** [comment]
Noted. I'll investigate this deeper.

**Comment by vinven7** [comment]
The error is the same as before:

`TypeError: Can't instantiate abstract class ConllDataset with abstract methods download                                 
home@spatula graph4nlp]$ python examples/pytorch/name_entity_recognition/main.py                 
starting build the dataset                                                                                              
Traceback (most recent call last):                                                                                        
File "examples/pytorch/name_entity_recognition/main.py", line 384, in <module>                                            
runner = Conll()                                                                                                      
File "examples/pytorch/name_entity_recognition/main.py", line 101, in __init__                                            self._build_dataloader()                                                                                              
File "examples/pytorch/name_entity_recognition/main.py", line 119, in _build_dataloader                                   tag_types=self.tag_types,                                                                                             
File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/typing.py", line 1231, in __new__                       
return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)                                                          
File "/home/synthesisproject/anaconda3/envs/vineeth/lib/python3.6/typing.py", line 1186, in _generic_new                  
return base_cls.__new__(cls)                                                                                        
TypeError: Can't instantiate abstract class ConllDataset with abstract methods download  `

**Comment by vinven7** [comment]
@SaizhuoWang Hi, I have opened some issues in the gaphnlp_demo repo. Could you please take a look at those as welll?

**Comment by SaizhuoWang** [comment]
Hi. I've followed the quick fix mentioned previously and it worked out fine for me. Please make sure the fix are made and try it again, thanks! We will also fix it in the source code in the coming version.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/26665465/157602699-5f136f47-396d-4421-9f93-72f882c65f9c.png">
