### ISSUE TITLE
What is `direction_option`?

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#531]
## ❓ Questions and Help

Couple of questions that I can't figure out neither from documentation nor from Github issues.

1. Direction_option option could be `undirected`, `bi_sep` or `bi_fuse`. What does it mean really?

2. Also the documentation is very confusing about relational graph support. It says:

- heterogenous graph
- As node

I saw [documentation](https://graph4ai.github.io/graph4nlp/guide/construction/dependencygraphconstruction.html#):

```
There are various dependency relations for dependency graph nodes. According to the need for down-tasks, we provide several options for: 

1. homogeneous graph, 
2. heterogeneous graph. Specifically, for heterogeneous graphs, we support not only various graph edge types but also support bipartite graphs, which regarding the edges as special nodes:
```

As per this documentation `heterogeneous` is supported. But then I see some other person asked about `heterogeneous` graph support and then it was said its not supported! Then I see even RGCN not supported. Super confusing. 

3. What is `n_etypes` in GGNN? If  heterogeneous is not supported then what edge_type really means?

**Comment by AlanSwift** [comment]
1. undirected, bi_sep or bi_fuse:
These options are named according to the message passing. Undierced: undirected graph. Bi-sep: directed graph, the forward and backward information are handled separately, Bi-fuse: directed graph. The forward and backward information are fused together.
I suggest to read our paper for this library: [survey paper](https://arxiv.org/pdf/2106.06090.pdf).

2. ``as_node`` is the levi-graph which we discussed in our paper. See #529.
3. n_etypes should be 1 now. This is just a placeholder. Currently it is just a directed homogeneous graph.

Note: the R-GNN is comming soon.

**Comment by smith-co** [comment]
- Currently all graphs are undirected, then what's the point of `bi_sep` `bi_fuse`? It should be set as `undirected` across all config files. Isn't it?  

- It was mentioned in this [issue](https://github.com/graph4ai/graph4nlp/issues/49) that RGCN would be supported in March. I looked through all config files, but can't really find out any examples using RGCN. Sincere apologies. Would you mind pointing to the RGCN implementation?

<img width="733" alt="Screen Shot 2022-03-30 at 12 24 37" src="https://user-images.githubusercontent.com/102386930/160914786-9d183a60-d87f-41d8-86ef-9d7394df85b6.png">

**Comment by AlanSwift** [comment]
1. Sorry. I just want to say we just support homogeneous (directed or undirected) graphs or transformed levi-graph (``as_node``).
2. This feature is under developing and there is no stable branch.

**Comment by smith-co** [comment]
@AlanSwift thanks for your response. For `2`, I would not mind even to try out this feature if you give me a branch and do the beta testing 👍

**Comment by AlanSwift** [comment]
Thanks!

> @AlanSwift thanks for your response.
> 
> For `2`, I would not mind even to try out this feature if you give me a working branch and I can do the beta testing 👍
