### ISSUE TITLE
How to do ablation for the BPE?

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#532]
## ❓ Questions and Help

I want to disable BPE for the NMT example and see with and without BPE.

How can I do that? Where the pre-processing is happening? Or is there a configurable parameter?

**Comment by AlanSwift** [comment]
I am afraid you have to implement it since this NMT example is just an example to guide the user.

**Comment by smith-co** [comment]
Sure, I can do that. But can you please provide me with any pointers?

**Comment by AlanSwift** [comment]
1. You can read the [semantic parsing](https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/semantic_parsing/graph2seq/main.py). This is a good example that shows how copy works.
Also the original paper: [pointer network](https://arxiv.org/abs/1704.04368).
2. You can design the special source and target vocabs. For example, they are 1k words. The source and target's vocabs can be the same in the top 1k words and with different words in the following. And the oov vocabulary can share the top 1k words with the source and target vocabulary.(copy from the top 1k and oov words)
