### ISSUE TITLE
What happens if we don't provide embedding for some tokens?

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#533]
## ❓ Questions and Help

What would happen if I don't provide embedding for all the tokens? I presume that would be initialized with random one-hot vector?

**Comment by hugochan** [comment]
> ## ❓ Questions and Help
> What would happen if I don't provide embedding for all the tokens? I presume that would be initialized with random one-hot vector?

@smith-co yes, out-of-vocab tokens will be randomly initialized from a uniform distribution. You can refer to the details [here](https://github.com/graph4ai/graph4nlp/blob/master/graph4nlp/pytorch/modules/utils/vocab_utils.py#L294).
