### ISSUE TITLE
Confused with num_heads parameter for GCN

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#541]
## ❓ Questions and Help

I am confused with:

a) I see `num_heads` in the GCN config file. 
https://github.com/graph4ai/graph4nlp/blob/master/examples/pytorch/nmt/config/dynamic_gcn.yaml#L22

I thought num_heads is only relevant for GAT for attention. Is it relevant for GCN? If yes, please correct me.

b) What is the `top_k_neigh` config param? How should I use it?

**Comment by AlanSwift** [comment]
1) This parameter has no relation to GNN. It is for dynamic graph construction which has multi-head attention.
2) This is for dynamic graph's graph sparsing mechanism.
Please refer to our paper's dynamic graph section. [paper](https://arxiv.org/abs/2106.06090)
