### ISSUE TITLE
tgt_emb_as_output_layer config parameter

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#542]
## ❓ Questions and Help

I do not understand `tgt_emb_as_output_layer` parameter.

```
    tgt_emb_as_output_layer: bool, default=False
        When this option is set ``True``, the output projection layer(It is used to project RNN encoded # noqa
        representation to target sequence)'s weight will be shared with the target vocabulary's embedding. # noqa
```

For some example, I see it is set to `TRUE` while for some it is `False`.

Can anyone please explain this parameter?

**Comment by AlanSwift** [comment]
This is determined according to the specific experimental results.

**Comment by smith-co** [comment]
@AlanSwift not quite sure what you meant? Is it a hyper-parameter then?

**Comment by AlanSwift** [comment]
Yes. It is a hyper-parameter.

**Comment by smith-co** [comment]
@AlanSwift `This is determined according to the specific experimental results` Can you please explain?

**Comment by smith-co** [comment]
@AlanSwift when should I set it and why?

**Comment by smith-co** [comment]
@AlanSwift should I set it for a classification task?

**Comment by AlanSwift** [comment]
You have to tune this parameter. There is no clear conclusion.
