### ISSUE TITLE
Confusion about parameters

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#544]
## ❓ Questions and Help

I am confused about the following parameters?

```
    sim_metric_type: 'weighted_cosine'
    num_heads: 1
    top_k_neigh: null
    epsilon_neigh: 0.5
    smoothness_ratio: 0.1
    connectivity_ratio: 0.05
    sparsity_ratio: 0.1
```

1. Are these parameters specific to any specific GNN i.e., GCN, GAT, GGNN, or for GraphSage? 
3. Or they are generic and applicable to all?

**Comment by hugochan** [comment]
> ## ❓ Questions and Help
> I am confused about the following parameters?
> 
> ```
>     sim_metric_type: 'weighted_cosine'
>     num_heads: 1
>     top_k_neigh: null
>     epsilon_neigh: 0.5
>     smoothness_ratio: 0.1
>     connectivity_ratio: 0.05
>     sparsity_ratio: 0.1
> ```
> 
>  1. Are these parameters specific to any specific GNN i.e., GCN, GAT, GGNN, or for GraphSage?
> 2. Or they are generic and applicable to all?

@smith-co thanks for your interest to the library! These are parameters related to dynamic graph construction and don't depend on specific GNNs. You might want to refer to [library documentation](https://graph4ai.github.io/graph4nlp/guide/construction/dynamic_graph_construction.html#guide-dynamic-graph-construction) for more details.

**Comment by AlanSwift** [comment]
This issue will be closed. Feel free to reopen it if needed.
