### ISSUE TITLE
Is there a way to visualize the GraphData?

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#547]
## ❓ Questions and Help

I am wondering whether is there a way to visualize the `GraphData` object?

Currently, I am doing the following:

```
import networkx as nx
import dgl
import matplotlib.pyplot as plt
from networkx.drawing.nx_pydot import write_dot

graph_data is a GraphData object.

graph_dgl = graph_data.to_dgl()
graph_nx = dgl.to_networkx(graph_dgl)
nx.draw(graph_nx, width=0.03, with_labels=True)
plt.show()
plt.savefig('foo.pdf')
write_dot(graph_nx, "foo.dot")
```

This is how I am visualizing the `GraphData` object. But `DGL` does not preserve the "text", i.e. tokens in the node. So I am wondering is there some other API that I can use to visualize the GraphData object with the "token" values itself.

Any pointers welcome.

**Comment by SaizhuoWang** [comment]
Currently `GraphData` does not support the feature of visualization. You may convert it to another type (e.g. networkx.Graph) for visualization.
