### ISSUE TITLE
visualize attention

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#548]
## ❓ Questions and Help

The library is super helpful, great work.

I would like to visualise attention like the following tutorial.
http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

Other libraries like [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) also support this feature.

Is there any optional argument to get attention information when I try to run translation example (NMT)?

Would really appreciate your help. 🙏 

<img width="716" alt="Screen Shot 2022-04-05 at 23 23 51" src="https://user-images.githubusercontent.com/102387185/161909676-2d409204-89c8-44c9-b0eb-fe99ec9f542a.png">

**Comment by schenglee** [comment]
Thank you very much for your feedback, unfortunately, we don't support attention visualization yet, we may consider putting it in the roadmap in the future, if you are interested in it, we welcome your PR!

**Comment by code-rex1** [comment]
@schenglee can you provide some pointers and I would be happy to help.

**Comment by smith-co** [comment]
@schenglee I would be interested to contribute in this pull request. Can you please provide some pointers?

**Comment by AlanSwift** [comment]
This issue will be closed. Feel free to reopen it if needed.
