### ISSUE TITLE
How to do hyperparameter optimization?

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#552]
## ❓ Questions and Help

I would like to do try out different hyperparameters and compare their performance for the NMT example. 

There are libraries like the `Hyperopt` library for tuning.

I would be interested to know is there a programmatic way to try out automated hyperparameter tuning option. Any ideas welcome.

**Comment by schenglee** [comment]
For hyperparameter tuning, please refer to issue #553, thank you for your feedback.
