### ISSUE TITLE
Parameters for hyperparameter tuning

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#553]
## ❓ Questions and Help

Here you have presented a Graph2Seq and Graph2Tree model. I would like to know what are the search space I should use for these Graph2Seq and Graph2Tree model.

Would be really interested to know what should be the reasonable values for different graph variants as well. 

I had look into your paper [Graph4NLP survey](http://arxiv.org/abs/2106.06090) to find out the reasonable value for tuning. Unfortunately, the survey does not shed light into this.

Would really appreciate your feedback about reasonable values for the hyper parameters?

**Comment by schenglee** [comment]
This is a nice question, we have put this issue into our TODO list, and we will soon build a document that could help hyperparameter tuning, stay tuned, please.

**Comment by code-rex1** [comment]
@schenglee wondering do you have any update on this issue? 🙏

**Comment by schenglee** [comment]
Please refer here: https://docs.google.com/spreadsheets/d/1JrlGtr0uaafZmd31P1P_z6uevjxLSVTX6uJbvWy5fsk/edit#gid=0
