### ISSUE TITLE
RGCN feature and branch

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#554]
## ❓ Questions and Help

I am investigating using this library but for my use case I have to try out the RGCN graph.

I see the following active branch for `RGCN`:

https://github.com/graph4ai/graph4nlp/commits/rgcn

I am more than happy to try out and beta-testing the `RGCN` graph for an `NMT` task. 

Any help is appreciated.

**Comment by xiao03** [comment]
Hi @code-rex1, thanks for your interests. As you can see, the work is currently in progress and not ready for testing. Please do not open similar issues. Your patience would be much appreciated.

**Comment by code-rex1** [comment]
@xiao03 can you please help or provide any pointers?

**Comment by code-rex1** [comment]
@xiao03 wondering whether there is any update? Can I take the `RGCN` code from your branch and try it out for the NMT example? 

Please help 🙏 🙏 🙏

**Comment by code-rex1** [comment]
@xiao03 wondering any update in this regard?
