### ISSUE TITLE
Reference paper for the NMT example

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#555]
## ❓ Questions and Help

Can anyone please refer me to the reference paper for the [NMT](https://github.com/graph4ai/graph4nlp/tree/master/examples/pytorch/nmt) example?

**Comment by nashid** [comment]
@AlanSwift, can you please share your insight?

**Comment by AlanSwift** [comment]
This is just an application of our library. There is no extract reference paper.

**Comment by nashid** [comment]
@AlanSwift got it. Is the high-level architecture of the model described in the document or in a tutorial? I cant find any. Any help to provide more details about the model be super helpful.

**Comment by AlanSwift** [comment]
Currently, there is no specific architecture for each application.

**Comment by nashid** [comment]
@AlanSwift I am confused about the initializaiton of the edge weights. I understand the node embeddings are initialized with word2vec (or BERT) before feeding to the GNN encoder.

But how the edge embeddings are initialized? Can you please explain?

**Comment by nashid** [comment]
@AlanSwift can you please help with the above query?

**Comment by AlanSwift** [comment]
Currently, the edge only contains connection signals. It doesn't have embeddings.

**Comment by nashid** [comment]
@AlanSwift little bit confused. I see this in the configuration:

```
if self.use_edge_weight:
   edge_weight = graph.edge_features['edge_weight']
```

So I thought I was using edge weights. But you are saying currently, edge does not have weight.

In that case, how the edge information helps?

**Comment by AlanSwift** [comment]
Currently, the GNNs such as GCN, GraphSage, GAT, GGNN only use connections.

**Comment by nashid** [comment]
@AlanSwift got it. Are you aware of any work in the literature that only uses edge for connection signal? I am already looking into your survey paper.

**Comment by nashid** [comment]
@AlanSwift can you please help us with the above query?
