### ISSUE TITLE
RGCN implementation

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#566]
## ❓ Questions and Help

RGCN implementation is in the feature implementation phase to the best of my understanding. I wonder how long would it take for the next release?

**Comment by hugochan** [comment]
@nashid thanks for checking in! Yes, we have finished the implementation and testing of RGCN. We will release a new version very soon with RGCN and other new features. Currently, we are actively testing the other features which we are planning to release together with RGCN. Please stay tuned!

**Comment by nashid** [comment]
@hugochan this is great news. Do you have any timeline in mind?

**Comment by hugochan** [comment]
> @hugochan this is great news. Do you have any timeline in mind?

We are aiming to release the new version in June.

**Comment by code-rex1** [comment]
@hugochan when this would be released? Do you have a timeline in mind?
