### ISSUE TITLE
NMT with custom graph

### ISSUE THREAD

**Issue by Nolanogenn** [graph4ai/graph4nlp#568]
Hi and thanks for this library.
Since it is not very clear from the examples / documentation, I wanted to ask whether is it possible to train an NMT model starting from custom graphs (which I currently store in several GraphData objects, one per sentence).
Thanks in advance!

**Comment by AlanSwift** [comment]
Sorry for the late reply. Do you still have problems with customizing the dataset?

**Comment by sulisetyowidodo** [comment]
Hi AlanSwift
I have a problem in reproduce NMT task with custom graph..
Can you help me step by step for this task?
Thanks.
