### ISSUE TITLE
Contrastive learning with graph neural network

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#569]
## 🚀 Feature
It would be awesome if the framework provides an example of contrastive learning with GNN.
For example, an implementation similar to SimCLR would be great.

**Comment by hugochan** [comment]
@smith-co thanks for your interest to our library and for your suggestion! We are always happy to implement more SOTA GNN models for NLP tasks. Can you share more context (e.g., any relevant paper on contrastive learning with GNN for NLP) to help us understand why you think this will be a great example to include in the library?

**Comment by AlanSwift** [comment]
This issue will be closed. Feel free to reopen it if needed.
