### ISSUE TITLE
make -j4 have. a bug on M1 macbook

### ISSUE THREAD

**Issue by qmnxxy** [graph4ai/graph4nlp#570]
## ❓ Questions and Help
/Users/lvkun/code/dgl/src/runtime/semaphore_wrapper.cc:73:17: error: use of undeclared identifier 'sem_timedwait'
/Users/lvkun/code/dgl/src/runtime/semaphore_wrapper.cc:73:17: error: use of undeclared identifier 'sem_timedwait'
  while ((ret = sem_timedwait(&sem_, &ts) != 0) && errno == EINTR) {
                ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/dgl.dir/src/runtime/semaphore_wrapper.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/dgl.dir/all] Error 2
make: *** [all] Error 2

and i don't solve this problem

**Comment by hugochan** [comment]
> ## ❓ Questions and Help
> /Users/lvkun/code/dgl/src/runtime/semaphore_wrapper.cc:73:17: error: use of undeclared identifier 'sem_timedwait' /Users/lvkun/code/dgl/src/runtime/semaphore_wrapper.cc:73:17: error: use of undeclared identifier 'sem_timedwait' while ((ret = sem_timedwait(&sem_, &ts) != 0) && errno == EINTR) { ^ 1 warning and 1 error generated. make[2]: *** [CMakeFiles/dgl.dir/src/runtime/semaphore_wrapper.cc.o] Error 1 make[2]: *** Waiting for unfinished jobs.... make[1]: *** [CMakeFiles/dgl.dir/all] Error 2 make: *** [all] Error 2
> 
> and i don't solve this problem

@qmnxxy Can you share more context (e.g., your pytorch version, graph4nlp version, what are you trying to achieve) with us to reproduce this error?

**Comment by AlanSwift** [comment]
This issue will be closed. Feel free to reopen it if needed.
