### ISSUE TITLE
RGCN implementation

### ISSUE THREAD

**Issue by nashid** [graph4ai/graph4nlp#573]
## ❓ Questions and Help

It's quite a while now. So following up. Wondering whether the RGCN implementation is available now in a branch? 

I wonder how long would it take for the next release?

**Comment by nashid** [comment]
@AlanSwift wondering do you have any update 🙏 ?

**Comment by AlanSwift** [comment]
Sorry for the late reply. It will come soon. We have delayed it since we have been busy the past two months.

**Comment by smith-co** [comment]
@AlanSwift I am also waiting for this feature. Any idea when this feature would be available? Would appreciate your help.

**Comment by AlanSwift** [comment]
As the reply in the roadmap, the RGCN will come soon with the next release in about two weeks.

**Comment by smith-co** [comment]
@AlanSwift great work with the library. Wondering when the RGCN would be available?

**Comment by AlanSwift** [comment]
Please refer to our roadmap for the RGCN. This issue will be closed.
