### ISSUE TITLE
How to create data.pt, vocab.pt, and label.pt for custom dataset?

### ISSUE THREAD

**Issue by firqaaa** [graph4ai/graph4nlp#574]
## ❓ Questions and Help

I have follow your tutorial on how to using graph4nlp for text classification using the trec data. So i try to create custom dataset for my imdb sentiment analysis. I have create all the .txt files both train and test. After that i change the .yaml file, create the custom dataset using Text2LabelDataset, and run the same code. Everything is fine but in the process it take very long time and still not start the training process. Another things that i consider is there are three files that i am still not have in the ./data/imdb/processed/dependency_graph that is data.pt, vocab.pt, and label.pt. How i can get these three files?

**Comment by AlanSwift** [comment]
Can you give the statistics such as sample amount, and mean token number in a sentence of your corpus?

**Comment by AlanSwift** [comment]
For both train and test split.

**Comment by AlanSwift** [comment]
I think you had better check whether StanfordCoreNLP runs successfully. For example, you can input "top" in your terminal and find the java process.
