### ISSUE TITLE
Support for transformer as the decoder

### ISSUE THREAD

**Issue by smith-co** [graph4ai/graph4nlp#575]
🚀 Feature

In the current implementation, RNNs are used as the decoder. 

I think it would be great to have Transformer as the decoder.

Wondering whether this feature is already under consideration.

Also if support the transformer implementation, when that feature would be availble?

**Comment by AlanSwift** [comment]
Thanks for your interest in the library.
We agree that transformer is needed and it is on schedule. I have replied it in https://github.com/graph4ai/graph4nlp/issues/496#issuecomment-1207130759.
