### ISSUE TITLE
Error while running Text Classification pipeline.

### ISSUE THREAD

**Issue by NageshMashette** [graph4ai/graph4nlp#580]
While running the below code :

!python -m examples.pytorch.text_classification.run_text_classifier -config examples/pytorch/text_classification/config/trec/gat_bi_fuse_constituency.yaml

, for the location (out/trec/gat_bi_fuse_constituency_ckpt), i am getting the error  **OSError: [Errno 30] Read-only file system: 'out'**

**Comment by AlanSwift** [comment]
Hello!
Sorry for the inconvenience.
I have installed the library on a new machine with V100 GPU, ubuntu 20 system. However, I can't reproduce the error message. Please provide us with more specific details such as environment, gpu, et.al.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/18572829/195552469-edb73485-3f10-4504-ae23-67efb3d6eb0e.png">

**Comment by AlanSwift** [comment]
This issue will be closed. Please reopen it if you have any problems.
